sudo: false
language: python
python:
  - "3.6"
cache: 'pip'

env:
  - TZ=UTC

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - molo scaffold testapp --require molo.servicedirectory --include molo.servicedirectory ^servicedirectory/
  - pip install -e testapp
  - flake8
  - py.test --cov=molo --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "ANT/oHJW8YUwFAAdTAbKNoOkaQkdlvUsMBsugghUMr8JVHOGlkbMQFjAoAgabHEot9l538msYvSRPpPh19XUirjEMwsMAP4Qg3mewe0dpib2ebFICtR7KqBARMpY6/AgrI29H3yDheZUu3jBAD2n1x+fWb1yRvFHkyKr9v/AXenOnYHJ/TGALgGytcGWO//IHTy7osTenjp7gqO9lrKFAfx/wpzXw2AABK+CrOcndpiw1sc/xJ5BDI91C5Y9tOESUX5YRXqWSAg2lMcuYav6pRcHvZF9BHD2QYA2iz8bpNIi+EI/3HRMNAZsQhYEBr+4Z2+V4TmoXc1XVz5IJ3NMvrALfxetJMwqSLOj8eShvckMEHa5Tu526Py/3YHI10WPC5DNExwD5/UoYjA3HIFgqCbUE7AM12rPMJzyWHJ08WB7GSZQDzq9orcRkl6w7m1aniMCfKfF9E7bYcd3BLYGE5/N0FwLtiFwkFiAW+Afe7LAcLMqlszjINA8do2TUYHlN8QtCyTVD+VNQN3GeM/VqbnJbMdkk9Zoz43sdGQYMl7ZatkdDtpeJbyWPGax8cvMHUSfbZhVlHSkOxJBlXMX9yufb7tWGZtMCyJwBZkjnBBx55eSSeaNydyKsRGN1Gg4aT5krixKf1nvwsWaLRFQlBsys1a3tfUSAJ1QHeK5Rs8="
  on:
    tags: true
    python: 3.6

notifications:
  slack: praekeltfoundation:mgvd7PsJynKvMoximpSmuusw
