sudo: false
language: python
python:
  - "3.6"
cache: 'pip'

env:
  - TZ=UTC

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - molo scaffold testapp --require molo.servicedirectory --include molo.servicedirectory ^servicedirectory/
  - pip install -e testapp
  - flake8
  - py.test --cov=molo --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: praekelt.org
  password:
    secure: F+sSpvgrSrOfrXFiivKkCoYnb0n1piERsrSZJyi0bi7BkHLyiIks6S/LVXdTFk8tDTa8R/n04Govxsulc+xMIbnt/f5pBVo8JIanFZakxDE8qah2Y0NvsO+tz4M8ftbOfdjgG1meBEtj0pk2Vt0vUWk6oz74DuoB1prDy0S4fz7fO9e0xQqVS91/xYzlhjTMuZ2LAZtTo/x2NYoq9X3lkgLcjNkBPL5I22X3hwCopLEILWdUC6FB01T/n8X8am4j48dUqk7TGksA8Lyap6+fmDZ5iLPU9ZqAmyzrxJa4rCi4UgcQDFz1cp1dsoV8dpEz9vIiR//KuIVAZ35XDAZdimJEGqXEwpkJP8B1qabmOHPHPl1OrA6cXWbs6KfZMY+Z2F2xf67RwTROatVrBevrVBpczzGhKUI/CXS7lUbIg3GFNhPjOssPCcDl1XPsFI8O7wYpu3WBM8ZG3cH343O6Dap5bK+5Lg5LCU+gjG7e3hYpbOCyrXdaJqPs1OXPCR3NoxfeeJHI2QTDNfYA30AVDk5Xr5RGyDhHp0ZpwnVkReFLNrfMOL5Y/M3Dv2yo2K9F1nE8GAKZjd3el5tu1VAhV3+jkpGNDi6AMycW2XmPeWF3+UM9mX5NjammTpv4YB2T49Gke7FB+JLu/sEoO/C7ZQ5BIFUuJjN8C/ORvo0qvv8=
  on:
    tags: true
    python: 3.6

notifications:
  slack: praekeltfoundation:mgvd7PsJynKvMoximpSmuusw
